# Generated by Django 5.0.7 on 2024-08-08 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productline'),
    ]

    operations = [
        migrations.AddField(
            model_name='productline',
            name='order_by',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProductLineImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alter_text', models.CharField(max_length=100)),
                ('image_url', models.ImageField(upload_to='product_images/')),
                ('order_by', models.BooleanField(default=False)),
                ('productline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productline_image', to='product.productline')),
            ],
        ),
    ]
